<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ENG_commonModal__close</name>
   <tag></tag>
   <elementGuidId>26cf967b-e8b3-4a9b-aaeb-b790306d216b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SW']/div/div[2]/div[2]/div/section/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.commonModal__close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section >> internal:has-text=&quot;Personal AccountMyBiz Account Mobile Number ‎+91Continue Or Login/Signup With By&quot;i >> span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3f86b54-5546-4215-adde-a6b894d9bac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>closeModal</value>
      <webElementGuid>13295742-f253-41a4-9bca-cd6716cc9ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>commonModal__close</value>
      <webElementGuid>27a49bd7-3f6a-40e5-8b6a-1973a58954d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SW&quot;)/div[@class=&quot;landingContainer eng&quot;]/div[@class=&quot;headerOuter&quot;]/div[@class=&quot;imageSliderModal modal displayBlock modalLogin dynHeight personal&quot;]/div[@class=&quot;imageSlideContainer&quot;]/section[@class=&quot;modalMain tcnFooter&quot;]/span[@class=&quot;commonModal__close&quot;]</value>
      <webElementGuid>632b90b6-fb45-4e94-911d-31f80e2ecb3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SW']/div/div[2]/div[2]/div/section/span</value>
      <webElementGuid>f45f6e76-7580-46b6-b28a-3e60e4f4337a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/span</value>
      <webElementGuid>b1fba2d8-5637-40a1-9872-58dac52fea57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
