<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hotels  Hotels</name>
   <tag></tag>
   <elementGuidId>8669cdaa-a56c-4e52-bb50-97f008e84aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SW']/div/div[2]/div/div/nav/ul/li[2]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.menu_Hotels > span > a.headerIcons.makeFlex.hrtlCenter.column</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hotels&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b1a0b34-1629-40ce-bf4c-b35b9b6c5004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.makemytrip.com/hotels/</value>
      <webElementGuid>03a04298-c2e8-43af-8d0f-1e651ad2ee56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headerIcons makeFlex hrtlCenter column</value>
      <webElementGuid>ab9553ef-2ee6-47f4-87ed-1f4acd74c037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Hotels  Hotels </value>
      <webElementGuid>43e6fe19-017d-47ed-b2ba-a837f6b0a618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SW&quot;)/div[@class=&quot;landingContainer eng&quot;]/div[@class=&quot;headerOuter&quot;]/div[@class=&quot;chHeaderWrapper navOnly&quot;]/div[@class=&quot;chHeaderContainer&quot;]/nav[1]/ul[@class=&quot;makeFlex font12 headerIconsGap&quot;]/li[@class=&quot;menu_Hotels&quot;]/span[1]/a[@class=&quot;headerIcons makeFlex hrtlCenter column&quot;]</value>
      <webElementGuid>a1123189-4226-40db-824b-637358347120</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SW']/div/div[2]/div/div/nav/ul/li[2]/span/a</value>
      <webElementGuid>0513480d-7def-4595-90d1-60da51b3eb91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.makemytrip.com/hotels/')]</value>
      <webElementGuid>7735c22b-405f-4366-8066-59de0dcdd055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span/a</value>
      <webElementGuid>a4a162a2-eb9b-43b1-abe8-8dcde2348ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.makemytrip.com/hotels/' and (text() = ' Hotels  Hotels ' or . = ' Hotels  Hotels ')]</value>
      <webElementGuid>6bf24c5b-525c-4ce0-876d-bcfd3a1d957c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
