<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ENG_commonModal__close</name>
   <tag></tag>
   <elementGuidId>615f8bdc-6bbb-472e-a47b-9e6935260059</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SW']/div/div[2]/div[2]/div/section/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.commonModal__close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section >> internal:has-text=&quot;Personal AccountMyBiz Account Mobile Number ‎+91Continue Or Login/Signup With By&quot;i >> span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e7e49058-8b11-4669-b962-85266e175579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>closeModal</value>
      <webElementGuid>e7b684a7-cee9-49b2-908c-2c7851b84121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>commonModal__close</value>
      <webElementGuid>b89625b0-a699-4eb8-af6f-a79df9ff1d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SW&quot;)/div[@class=&quot;landingContainer eng&quot;]/div[@class=&quot;headerOuter&quot;]/div[@class=&quot;imageSliderModal modal displayBlock modalLogin dynHeight personal&quot;]/div[@class=&quot;imageSlideContainer&quot;]/section[@class=&quot;modalMain tcnFooter&quot;]/span[@class=&quot;commonModal__close&quot;]</value>
      <webElementGuid>af6a7144-a961-4996-9b44-d0c4bf4a9fe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SW']/div/div[2]/div[2]/div/section/span</value>
      <webElementGuid>30f5f800-10c7-4983-be55-1770abbf0668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/span</value>
      <webElementGuid>80040a96-e9ed-4136-9936-1cec678be155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
